server:
  port: 8083

spring:
  application:
    name: CALIFICACION-MICROSERVICE
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017
      database: microservice_calificacion
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/